export const API_SUCCESS_LOGIN = 'API_SUCCESS_LOGIN'
export const API_LOGOUT = 'API_LOGOUT'
export const API_FAILURE_LOGIN = 'API_FAILURE_LOGIN'
export const API_STARTED_LOGIN = 'API_STARTED_LOGIN'

export const API_SUCCESS_CHAMPIONS = 'API_SUCCESS_CHAMPIONS'
export const API_SUCCESS_CHAMPION = 'API_SUCCESS_CHAMPION'
export const API_FAILURE_CHAMPION = 'API_FAILURE_CHAMPION'
export const API_STARTED_CHAMPION = 'API_STARTED_CHAMPION'

export const API_SUCCESS_ITEMS = 'API_SUCCESS_ITEMS'
export const API_SUCCESS_ITEM = 'API_SUCCESS_ITEM'
export const API_FAILURE_ITEM = 'API_FAILURE_ITEM'
export const API_STARTED_ITEM = 'API_STARTED_ITEM'

export const SWITCH_THEME = 'SWITCH_THEME'

export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const NEW_BUILD = 'NEW_BUILD'
export const SELECTED_BUILD = 'SELECTED_BUILD'
