export const API_SUCCESS_LOGIN = 'API_SUCCESS_LOGIN'
export const API_LOGOUT = 'API_LOGOUT'
export const API_FAILURE_LOGIN = 'API_FAILURE_LOGIN'
export const API_STARTED_LOGIN = 'API_STARTED_LOGIN'

export const API_SUCCESS_CHAMPIONS = 'API_SUCCESS_CHAMPIONS'
export const API_SUCCESS_CHAMPION = 'API_SUCCESS_CHAMPION'
export const API_FAILURE_CHAMPION = 'API_FAILURE_CHAMPION'
export const API_STARTED_CHAMPION = 'API_STARTED_CHAMPION'

export const SWITCH_THEME = 'SWITCH_THEME'
